# Generated by Django 6.0.2 on 2026-02-28 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentOrders",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "order_no",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(db_index=True, default="new", max_length=32),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("status", models.CharField(default="processing", max_length=32)),
                ("req_hash", models.CharField(max_length=64)),
                ("snap_shot", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idem_key",
                        to="orders.paymentorders",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
